#!/usr/bin/env python
"""
Simple script to convert ECA/ELA site to GeoJson EPSG:27700
"""
import json
import sys

import pandas as pd
from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    df = pd.read_html(
        f"https://ecaelastats.site/{sys.argv[1]}_refs.php",
        storage_options={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"})

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    for _, row in df[0].iterrows():
        try:
            point = transformer.transform(
                float(row['Latitude']), float(row['Longitude']))
            features.append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [int(p) for p in point],
                },
                "properties": {
                    "name": row.iloc[1],
                    "reference": row.iloc[0],
                }
            })
        except Exception as e:
            print(row, file=sys.stderr)
            print(repr(e), file=sys.stderr)
            continue
    json.dump(geojson, sys.stdout, separators=(',', ':'))
