#!/usr/bin/env python
import json
import sys

from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    with open(sys.argv[1], encoding='utf-8') as input_file:
        data = json.load(input_file)

        for n, row in enumerate(data):
            try:
                if not row['reference_code'].startswith('GB-'):
                    continue
                point = transformer.transform(
                    float(row['latitude']), float(row['longitude']))
                features.append({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [round(p) for p in point],
                    },
                    "properties": {
                        "reference": row["reference_code"],
                        "name": row["name"],
                    }
                })
            except Exception as err:
                print(n, err, row, file=sys.stderr)
    json.dump(geojson, sys.stdout, separators=(',', ':'))
