#!/usr/bin/env python
"""
Simple script to convert UK BOTA to GeoJson EPSG:27700
"""
import json
import sys

from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    for input_filename in sys.argv[1:]:
        with open(input_filename, encoding='utf-8') as input_file:
            data = json.load(input_file)
            for n, input_geojson in enumerate(data['features']):
                try:
                    point = transformer.transform(
                        float(input_geojson['geometry']['coordinates'][1]), float(input_geojson['geometry']['coordinates'][0]))
                    features.append({
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [round(p) for p in point],
                        },
                        "properties": {
                            "reference": input_geojson["properties"]["ref"],
                            "name": input_geojson["properties"]["name"],
                        }
                    })
                except Exception as err:
                    print(n, err, input_geojson, file=sys.stderr)
    json.dump(geojson, sys.stdout, separators=(',', ':'))
