#!/usr/bin/env python
import json
import sys

from pyproj import Transformer
import requests

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    offset = 0
    with requests.Session() as session:
        while response := session.get(
            "https://parc-community.com/api/parks",
            params={"country": "GB", "limit": 1000, "offset": offset}
        ).json():
            offset += 1000
            for n, row in enumerate(response):
                try:
                    point = transformer.transform(
                        float(row['latitude']), float(row['longitude']))
                    features.append({
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [round(p) for p in point],
                        },
                        "properties": {
                            "reference": row["reference"],
                            "name": row["name"],
                        }
                    })
                except Exception as err:
                    print(n+offset, err, row, file=sys.stderr)
    json.dump(geojson, sys.stdout, separators=(',', ':'))
