#!/usr/bin/env python
"""
Simple script to convert UK BOTA to GeoJson EPSG:27700
"""
import csv
import json
import sys

from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    with open(sys.argv[1], newline='', encoding='utf-8-sig') as input_file:
        reader = csv.DictReader(input_file, delimiter=';')

        for n, row in enumerate(reader):
            try:
                point = transformer.transform(
                    float(row['Lat']), float(row['Lon']))
                features.append({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [round(p) for p in point],
                    },
                    "properties": {
                        "reference": row["Ref"],
                        "name": row["Nazev"],
                    }
                })
            except Exception as err:
                print(n, err, row, file=sys.stderr)
    json.dump(geojson, sys.stdout, separators=(',', ':'))
