#!/usr/bin/env python
"""
Simple script to convert UK BOTA to GeoJson EPSG:27700
"""
import csv
import json
import sys

from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    with open(sys.argv[1], newline='', encoding='cp1252') as input_file:
        reader = csv.DictReader(input_file)

        for row in reader:
            if row["Scheme"] != "UKBOTA":  # Skip non-UKBOTA
                continue
            point = transformer.transform(
                float(row['Lat']), float(row['Long']))
            features.append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [round(p) for p in point],
                },
                "properties": {
                    "reference": row["Reference"],
                    "name": row["Name"],
                }
            })
    json.dump(geojson, sys.stdout, separators=(',', ':'))
