#!/bin/env python
"""
Simple script to convert ukrepeater site to GeoJson EPSG:27700
"""
import csv
import json
import sys

from pyproj import Transformer

if __name__ == "__main__":

    transformer = Transformer.from_crs(4326, 27700)

    features = []
    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    with open(sys.argv[1], newline='') as input_file:
        reader = csv.DictReader(input_file)

        for row in reader:
            if len(sys.argv) > 2:
                if row["band"] != sys.argv[2]:
                    continue

            if len(sys.argv) > 3:
                if sys.argv[3].lower() not in {"analogue", "digital"}:
                    raise RuntimeError("Invalid mode selection")
                if sys.argv[3].lower() == "analogue" and "A" not in row["Modes"]:
                    continue
                elif sys.argv[3].lower() == "digital" and row["Modes"] == "A":
                    continue

            point = transformer.transform(
                float(row['lat']), float(row['lon']))
            features.append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [int(p) for p in point],
                },
                "properties": {
                    "name": "{band} {Modes}".format(**row),
                    "reference": row["repeater"],
                }
            })
    json.dump(geojson, sys.stdout, separators=(',', ':'))
